[package]
name = "jakpago"
version = "0.1.0"
edition = "2024"
authors = ["psvm203 <psvm203@proton.me>"]

[dependencies]
gloo-console = "0.3.0"
gloo-net = "0.6.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
yew-hooks = "0.3.3"
