[package]
name = "jakpago"
version = "0.1.0"
authors = ["psvm203 <psvm203@proton.me>"]
edition = "2024"
description = "jakpago"
license = "MIT"
repository = "https://github.com/psvm203/jakpago"
keywords = ["game"]
categories = ["wasm"]

[dependencies]
gloo-console = "0.3.0"
gloo-net = "0.6.0"
gloo-storage = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_urlencoded = "0.7.1"
serde_yaml = "0.9.34"
sycamore = "0.9.1"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
yew-hooks = "0.3.3"
